//2016/3/10 14:14:30 郅小凯补充定义
//2016/3/18 13:05:03 增加键盘类型
//2016/3/29 11:35:52 增加灭火盘类型，简化部分名称

#ifndef _DEVICE_TYPE_DEFINE_H_
#define _DEVICE_TYPE_DEFINE_H_

#define DEVICE_TYPE_0                               0  	    //预留                                   	
#define DEVICE_FIRE_MCU                             1  	    //火灾报警控制器/火灾报警控制器（联动型）	
#define DEVICE_FIRE_LINK_MCU                        2  	    //消防联动控制器                         	
#define DEVICE_FIRE_ROOM_GRAPH_DIS                  3  	    //消防控制室图形显示装置                 	
#define DEVICE_FIRE_TRANS							4  	    //火警传输设备                   	 
#define DEVICE_TYPE_5                               5  	    //                                       	
#define DEVICE_TYPE_6                               6  	    //                                       	
#define DEVICE_TYPE_7                               7  	    //                                       	
#define DEVICE_TYPE_8                               8  	    //                                       	
#define DEVICE_TYPE_9                               9  	    //                                       	
#define DEVICE_FIRE_DIS_PANEL                       10 	    //火灾显示盘                             	
#define DEVICE_DETECT_LOOP                          11 	    //探测回路                               	
#define DEVICE_CONTROL_LOOP                         12 	    //控制回路                               	
#define DEVICE_POWER_SOURCE                         13 	    //主电源                                 	
#define DEVICE_POWER_SUPPLY                         14 	    //备用电源                               	
#define DEVICE_RECHARGE_CIRCUIT                     15 	    //充电电路                               	
#define DEVICE_TYPE_16                              16 	    //声光警报回路                           	
#define DEVICE_TYPE_17                              17 	    //                                       	
#define DEVICE_TYPE_18                              18 	    //预留                                   	
#define DEVICE_TYPE_19                              19 	    //                                       	
#define DEVICE_FIRE_DETECTOR                        20 	    //火灾探测器                             	
#define DEVICE_SMOKE_FIRE_DETECTOR                  21 	    //感烟火灾探测器                         	
#define DEVICE_POINT_ION_SMOKE_FIRE_DETECTOR        22 	    //点型离子感烟火灾探测器                 	
#define DEVICE_POINT_PY_SMOKE_FIRE_DETECTOR         23 	    //点型光电感烟火灾探测器                	 
#define DEVICE_LINEAR_SMOKE_FIRE_DETECTOR           24 	    //线型光束感烟火灾探测器                	 
#define DEVICE_ABS_SMOKE_FIRE_DETECTOR              25 	    //吸气式感烟火灾探测器                   	
#define DEVICE_TYPE_26                              26 	    //预留                                   	
#define DEVICE_TYPE_27                              27 	    //                                       	
#define DEVICE_TYPE_28                              28 	    //                                       	
#define DEVICE_TYPE_29                              29 	    //                                       	
#define DEVICE_FEEL_FIRE_DETECTOR                   30 	    //感温火灾探测器                         	
#define DEVICE_POINT_FEEL_FIRE_DETECTOR             31 	    //点型感温火灾探测器                     	
#define DEVICE_LINEAR_FEEL_FIRE_DETECTOR            32 	    //线型感温火灾探测器                     	
#define DEVICE_CABLE_LINEAR_FIRE_DETECTOR           33 	    //缆式线型火灾探测器                     	
#define DEVICE_TYPE_34                              34 	    //空气管式线型火灾探测器                 	
#define DEVICE_TYPE_35                              35 	    //线型光纤感温火灾探测器                 	
#define DEVICE_TYPE_36                              36 	    //                                       	
#define DEVICE_TYPE_37                              37 	    //预留                                   	
#define DEVICE_TYPE_38                              38 	    //                                       	
#define DEVICE_TYPE_39                              39 	    //                                      	 
#define DEVICE_FLAME_DETECTOR                       40 	    //火焰探测器                             	
#define DEVICE_POINT_IR_FIRE_DETECTOR               41 	    //点型红外火焰探测器                     	
#define DEVICE_LINEAR_UV_FIRE_DETECTOR              42 	    //点型紫外火焰探测器                     	
#define DEVICE_POINT_IR_UV_FIRE_DETECTOR            43 	    //点型复合式红外紫外火焰探测器           	
#define DEVICE_TYPE_44                              44 	    //预留                                   	
#define DEVICE_TYPE_45                              45 	    //                                       	
#define DEVICE_TYPE_46                              46 	    //                                       	
#define DEVICE_POINT_SMOKE_TEMP_FIRE_DETECTOR       47 	    //烟温复合探测器                                       	
#define DEVICE_TYPE_48                              48 	    //                                       	
#define DEVICE_TYPE_49                              49 	    //                                       	
#define DEVICE_MULTI_DETECTOR                       50 	    //多传感复合探测器                       	
#define DEVICE_SENSITISING_FIRE_DETECTOR            51 	    //感光火灾探测器                         	
#define DEVICE_IMAGE_FIRE_DETECTOR                  52 	    //图像型火灾探测器                       	
#define DEVICE_POINT_CO_FIRE_DETECTOR               53 	    //点型一氧化碳火灾探测器                 	
#define DEVICE_TYPE_54                              54 	    //预留                                  	 
#define DEVICE_TYPE_55                              55 	    //                                       	
#define DEVICE_TYPE_56                              56 	    //                                       	
#define DEVICE_TYPE_57                              57 	    //                                       	
#define DEVICE_TYPE_58                              58 	    //                                       	
#define DEVICE_TYPE_59                              59 	    //                                       	
#define DEVICE_TYPE_60                              60 	    //                                       	
#define DEVICE_HAND_FIRE_DETECTOR                   61 	    //手动火灾报警按钮                       	
#define DEVICE_FIRE_COCK_BUTTON                     62 	    //消火栓按钮                             	
#define DEVICE_URGENCY_START_BUTTON                 63 	    //紧急启动按钮                           	
#define DEVICE_URGENCY_STOP_BUTTON                  64 	    //紧急停止按钮                           	
#define DEVICE_URGENCY_START_STOP_BUTTON            65 	    //紧急启停按钮                                              	
#define DEVICE_TYPE_66                              66 	    //                                       	
#define DEVICE_TYPE_67                              67 	    //                                       	
#define DEVICE_TYPE_68                              68 	    //                                       	
#define DEVICE_TYPE_69                              69 	    //                                       	
#define DEVICE_TYPE_70                              70 	    //预留                                   	
#define DEVICE_MODULE                               71 	    //模块                                   	
#define DEVICE_INPUT_MODULE                         72 	    //输入模块                               	
#define DEVICE_OUTPUT_MODULE                        73 	    //输出模块                               	
#define DEVICE_INTPUT_OUTPUT_MODULE                 74 	    //输入/输出模块                          	
#define DEVICE_RELAY_MODULE                         75 	    //中继模块                               	
#define DEVICE_SHOUT_ISOLATOR                       76 	    //短路隔离器                             	
#define DEVICE_TYPE_77                              77 	    //预留                                   	
#define DEVICE_TYPE_78                              78 	    //                                       	
#define DEVICE_TYPE_79                              79 	    //                                       	
#define DEVICE_TYPE_80                              80 	    //                                       	
#define DEVICE_FIRE_ALARM_DEVICE                    81 	    //火灾警报装置                           	
#define DEVICE_FIRE_SOUND_LIGHT_ALARM_DEVICE        82 	    //火灾声光警报器                         	
#define DEVICE_FIRE_SOUND_ALARM_DEVICE              83 	    //火灾声警报器                           	
#define DEVICE_FIRE_LIGHT_ALARM_DEVICE              84 	    //火灾光警报器                           	
#define DEVICE_GAS_FREE_ALARM_DEVICE                85 	    //气体释放警报器                         	
#define DEVICE_POLICE_BELL                          86 	    //警铃                                   	
#define DEVICE_TYPE_87                              87 	    //预留                                   	
#define DEVICE_TYPE_88                              88 	    //                                       	
#define DEVICE_TYPE_89                              89 	    //                                       	
#define DEVICE_TYPE_90                              90 	    //                                       	
#define DEVICE_TYPE_91                              91 	    //                                       	
#define DEVICE_TYPE_92                              92 	    //                                       	
#define DEVICE_TYPE_93                              93 	    //                                       	
#define DEVICE_TYPE_94                              94 	    //                                       	
#define DEVICE_TYPE_95                              95 	    //                                       	
#define DEVICE_TYPE_96                              96 	    //                                       	
#define DEVICE_TYPE_97                              97 	    //                                       	
#define DEVICE_TYPE_98                              98 	    //                                       	
#define DEVICE_TYPE_99                              99 	    //                                       	
#define DEVICE_COMBUSTIBLE_GAS_ALARM_DEVICE         100	    //可燃气体报警控制器                     	
#define DEVICE_COMBUSTIBLE_GAS_PROBE                101	    //可燃气体探测器                         	
#define DEVICE_POINT_COMBUSTIBLE_GAS_PROBE          102	    //点型可燃气体探测器                     	
#define DEVICE_LINEAR_COMBUSTIBLE_GAS_PROBE         103	    //线型可燃气体探测器                     	
#define DEVICE_TYPE_104                             104	    //预留                                   	
#define DEVICE_TYPE_105                             105	    //                                       	
#define DEVICE_TYPE_106                             106	    //                                       	
#define DEVICE_TYPE_107                             107	    //                                       	
#define DEVICE_TYPE_108                             108	    //                                       	
#define DEVICE_TYPE_109                             109	    //                                       	
#define DEVICE_TYPE_110                             110	    //                                       	
#define DEVICE_TYPE_111                             111	    //                                       	
#define DEVICE_TYPE_112                             112	    //                                       	
#define DEVICE_TYPE_113                             113	    //                                       	
#define DEVICE_TYPE_114                             114	    //                                       	
#define DEVICE_TYPE_115                             115	    //                                       	
#define DEVICE_TYPE_116                             116	    //                                       	
#define DEVICE_TYPE_117                             117	    //                                       	
#define DEVICE_TYPE_118                             118	    //                                       	
#define DEVICE_TYPE_119                             119	    //                                       	
#define DEVICE_ELECTRICAL_CTAL_FIRE_DEVICE          120	    //电气火灾监控设备                       	
#define DEVICE_ELECTRICAL_CTAL_FIRE_PROBE           121	    //电气火灾监控探测器                     	
#define DEVICE_SURPLUS_CURRENT_ELECTRICAL_DETECTOR  122	    //剩余电流式电气火灾监控探测器           	
#define DEVICE_TEMP_ELECTRICAL_CTAL_FIRE_PROBE      123	    //测温式电气火灾监控探测器               	
#define DEVICE_FAULT_ARC_PROBE                      124	    //故障电弧探测装置                       	
#define DEVICE_TYPE_125                             125	    //预留                                   	
#define DEVICE_TYPE_126                             126	    //                                       	
#define DEVICE_TYPE_127                             127	    //                                       	
#define DEVICE_TYPE_128                             128	    //                                       	
#define DEVICE_TYPE_129                             129	    //                                       	
#define DEVICE_EMERGENCY_LAMPS_MCU                  130	    //应急照明控制器                         	
#define DEVICE_FIRE_EMERGENCY_FLAG_LAMPS            131	    //消防应急标志灯具                       	
#define DEVICE_FIRE_EMERGENCY_LED_LAMPS             132	    //消防应急照明灯具                      	 
#define DEVICE_FIRE_EMERGENCY_LAMPS_DEDICATED_USP   133	    //消防应急灯具专用应急电源               	
#define DEVICE_EMERGENCY_LAMPS_ALLOT_ELE_DEVICE     134	    //应急照明分配电装置                     	
#define DEVICE_TYPE_135                             135	    //预留                                   	
#define DEVICE_TYPE_136                             136	    //                                       	
#define DEVICE_TYPE_137                             137	    //                                       	
#define DEVICE_TYPE_138                             138	    //                                       	
#define DEVICE_TYPE_139                             139	    //                                       	
#define DEVICE_FIRE_DOOR_CONTROL                    140	    //防火门监控器                           	
#define DEVICE_NC_FIRE_DOOR                         141	    //常闭防火门                             	
#define DEVICE_NO_FIRE_DOOR                         142	    //常开防火门                             	
#define DEVICE_FIRE_DOOR_AUTO_NC_DEVICE             143	    //防火门电动闭门器                       	
#define DEVICE_FIRE_DOOR_MAGNETISM_FREE_DEVICE      144	    //防火门电磁释放器                       	
#define DEVICE_FIRE_DOOR_MAGNETISM_SWITCH           145	    //防火门门磁开关                         	
#define DEVICE_TYPE_146                             146	    //预留                                   	
#define DEVICE_TYPE_147                             147	    //                                       	
#define DEVICE_TYPE_148                             148	    //                                       	
#define DEVICE_TYPE_149                             149	    //                                       	
#define DEVICE_FIRE_DEVICE_POWER_CTAL_DEVICE        150	    //消防设备电源监控器                     	
#define DEVICE_POWER_VOLTAGE_SIGNAL_SENSOR          151	    //消防设备电源电压信号传感器             	
#define DEVICE_PORER_CURRENT_SIGNAL_SENSOR          152	    //消防设备电源电流信号传感器             	
#define DEVICE_PORER_VOLTAGE_CURRENT_SENSOR         153	    //消防设备电源电压/电流信号传感器        	
#define DEVICE_TYPE_154                             154	    //预留                                   	
#define DEVICE_TYPE_155                             155	    //                                       	
#define DEVICE_TYPE_156                             156	    //                                       	
#define DEVICE_TYPE_157                             157	    //                                       	
#define DEVICE_TYPE_158                             158	    //                                       	
#define DEVICE_TYPE_159                             159	    //                                       	
#define DEVICE_GAS_PUT_FIRE_CTAL_DEVICE             160	    //气体灭火控制器                         	
#define DEVICE_FOAM_PUT_FIRE_SYSTEM                 161	    //泡沫灭火系统                           	
#define DEVICE_DRY_POWER_PUT_FIRE_SYSTEM            162	    //干粉灭火系统                           	
#define DEVICE_CTRL_FIRE_EJECT_SMOKE_SYSTEM         163	    //防烟排烟系统                           	
#define DEVICE_CTRL_FIRE_SHUTTER_DEVICE             164	    //防火卷帘控制器                        	 
#define DEVICE_KEEP_OFF_SMOKE_VERTICAL_CTRL_DEVICE  165	    //挡烟垂壁控制装置                       	
#define DEVICE_FIRE_EMERGENCY_BROADCAS              166	    //消防应急广播                           	
#define DEVICE_FIRE_PHONE_HOST                      167	    //消防电话主机                           	
#define DEVICE_FIRE_DEVICE_EMERGENCY_POWER          168	    //消防设备应急电源                       	
#define DEVICE_SEND_DEVICE                          169	    //传输设备                               	
#define DEVICE_HOME_FIRE_SAFE_SYSTEM_DEVICE    		170	    //家用火灾安全系统控制中心监控设备       	
#define DEVICE_FIRE_WATER_LEVEL_CONTROL_DEVICE 		171	    //消防水位监视器                         	
#define DEVICE_FIRE_LIFT                       		172	    //消防电梯                               	
#define DEVICE_FIRE_ELECTRICAL_CTAL_DEVICE     		173	    //消防电气控制装置                       	
#define DEVICE_TYPE_174                        		174	    //预留                                   	
#define DEVICE_TYPE_175                        		175	    //                                       	
#define DEVICE_TYPE_176                        		176	    //                                       	
#define DEVICE_TYPE_177                        		177	    //                                       	
#define DEVICE_TYPE_178                        		178	    //                                       	
#define DEVICE_TYPE_179                        		179	    //                                       	
#define DEVICE_TYPE_180                        		180	    //                                       	
#define DEVICE_TYPE_181                        		181	    //                                       	
#define DEVICE_TYPE_182                        		182	    //                                       	
#define DEVICE_TYPE_183                        		183	    //                                       	
#define DEVICE_BLEED_INDICATOR_LAMP             	184	    // 放气指示灯     	
#define DEVICE_TYPE_185                        		185	    //                                       	
#define DEVICE_TYPE_186                        		186	    //                                       	
#define DEVICE_TYPE_187                        		187	    //                                       	
#define DEVICE_TYPE_188                        		188	    //                                       	
#define DEVICE_TYPE_189                        		189	    //                                       	
#define DEVICE_TYPE_190                        		190	    //                                       	
#define DEVICE_FIRE_PUMP                       		191	    //消防栓泵                               	
#define DEVICE_WATER_SPRAY_PUMP                		192	    //水喷雾泵                               	
#define DEVICE_FINE_WATER_SPRAY_PUMP           		193	    //细水雾泵                               	
#define DEVICE_STABILIVOLT_PUMP                		194	    //稳压泵                                 	
#define DEVICE_SPRAY_FILTER_PUMP               		195	    //喷淋泵                                 	
#define DEVICE_WATER_FILTER_PUMP               		196	    //雨淋泵                                 	
#define DEVICE_FOAM_FLUID_PUMP                 		197	    //泡沫液泵                               	
#define DEVICE_WATER_FLUID_SHOWER              		198	    //水流指示器                             	
#define DEVICE_ALARM_PUMP                      		199	    //报警阀                                 	
#define DEVICE_PRESSURE_SWITCH                 		200	    //压力开关                               	
#define DEVICE_PUMP_DRIVE_DEVICE               		201	    //阀驱动装置                             	
#define DEVICE_CTRL_FIRE_VALVE                 		202	    //防火阀                                 	
#define DEVICE_70_CTRL_FIRE_VALVE              		203	    //70度防火阀                             	
#define DEVICE_280_CTRL_FIRE_VALVE             		204	    //280度防火阀                            	
#define DEVICE_VENTILATION_AIR_CONDITION       		205	    //通风空调                               	
#define DEVICE_TUBE_NET_SOLENOID_VALVE         		206	    //管网电磁阀                             	
#define DEVICE_CTLR_SMOKE_EXHAUST              		207	    //防烟排烟风机                           	
#define DEVICE_EXHAUST_CTRL_FIRE_VALVE         		208	    //排烟防火阀                             	
#define DEVICE_NC_EXHAUST_OUTLET               		209	    //常闭送风口                             	
#define DEVICE_EXHAUST_OUTLET                  		210	    //排烟口                                 	
#define DEVICE_FIRE_WATER_GUN                  		211	    //消防水炮                               	
#define DEVICE_POWER_DRIVEN_DOOR               		212	    //电动门                                 	
#define DEVICE_EXHAUST_DEVICE                  		213	    //排烟机                                 	
#define DEVICE_BLOWING_IN_DEVICE               		214	    //送风机                                 	
#define DEVICE_RADIOTUBE                       		215	    //电磁阀                                 	
#define DEVICE_LIGHT_ELECTRIC                  		216	    //照明配电                               	
#define DEVICE_POWER_ELECTRIC                  		217	    //动力配电                               	
#define DEVICE_EMPTY_PRESSURE_DEVICE           		218	    //空压机                                 	
#define DEVICE_VALVE		                   		219	    //阀门                                   	
#define DEVICE_DISTRIBUTION_BOX                		220	    //配电箱                                 	
#define DEVICE_TYPE_221                        		221	    //预留                                   	
#define DEVICE_TYPE_222                        		222	    //预留                             	     
#define DEVICE_TYPE_223                        		223	    //预留                             	     
#define DEVICE_TYPE_224                        		224	    //预留                             	     
#define DEVICE_TYPE_225                        		225	    //预留                             	     
#define DEVICE_TYPE_226                        		226	    //预留                             	     
#define DEVICE_TYPE_227                        		227	    //预留                             	     
#define DEVICE_TYPE_228                        		228	    //预留                             	     
#define DEVICE_TYPE_229                        		229	    //预留                             	     
#define DEVICE_TYPE_LOOP_CARD                  		230	    //回路卡                             	 
#define DEVICE_TYPE_OPERATION_PANEL            		231	    //操作盘                             	 
#define DEVICE_TYPE_LINKAGE_PANEL              		232	    //联动盘    0xe8                         	 
#define DEVICE_DATA_LOG_UNIT                   		233	    //数据记录单元                            
#define DEVICE_TYPE_PRINTER                    		234	    //打印机                             	 
#define DEVICE_TYPE_KEY_BOARD                  		235	    //键盘                             	
#define DEVICE_TYPE_EXTINGUISH_PANEL           		236	    //灭火盘                            	
#define DEVICE_TYPE_SECURITY_DETECTOR          		237	    //防盗探测器                          	
                                               		
#define DEVICE_TYPE_ALARM_DEVICE			   		238	    //报警器件
#define DEVICE_TYPE_ROLLINTGDOOR_HALFDOWN      		239	    //卷帘半降
#define DEVICE_TYPE_ROLLINTGDOOR_ALLDOWN       		240	    //卷帘全降 
                                               		
#define DEVICE_DETECTOR_CLASS                  		241	    //探测器类
#define DEVICE_AUTO_TRANS_SWITCH    				242	    //自动转换开关
#define DEVICE_TYPE_243                        		243	    //预留                             	     
#define DEVICE_TYPE_244                        		244	    //预留                             	     
#define DEVICE_TYPE_245                        		245	    //预留                             	     
#define DEVICE_TYPE_246                        		246	    //预留                             	     
#define DEVICE_TYPE_247                        		247	    //预留                             	     
#define DEVICE_TYPE_248                        		248	    //预留                             	     
#define DEVICE_TYPE_249                        		249	    //预留                             	     
#define DEVICE_TYPE_250                        		250	    //预留   
#define DEVICE_TYPE_251                        		251	    //预留                             	     
#define DEVICE_TYPE_252                        		252		//预留                             	     
#define DEVICE_TYPE_253                        		253		//预留                             	     
#define DEVICE_TYPE_254                        		254		//预留 
#define DEVICE_TYPE_NON_EXISTENT			   		255	    //器件不存在   


#endif
