/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: new1font.h                                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 24                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  62A5 - 62A5                                        *
* Range enabled:  8B66 - 8B66                                        *
* Range enabled:  4FE1 - 4FE1                                        *
* Range enabled:  606F - 606F                                        *
* Range enabled:  5DF2 - 5DF2                                        *
* Range enabled:  62E8 - 62E8                                        *
* Range enabled:  901A - 901A                                        *
* Range enabled:  672A - 672A                                        *
* Range enabled:  6545 - 6545                                        *
* Range enabled:  969C - 969C                                        *
* Range enabled:  4E3B - 4E3B                                        *
* Range enabled:  7535 - 7535                                        *
* Range enabled:  6545 - 6545                                        *
* Range enabled:  969C - 969C                                        *
* Range enabled:  8BF7 - 8BF7                                        *
* Range enabled:  5C3D - 5C3D                                        *
* Range enabled:  5FEB - 5FEB                                        *
* Range enabled:  5904 - 5904                                        *
* Range enabled:  7406 - 7406                                        *
* Range enabled:  53D1 - 53D1                                        *
* Range enabled:  9001 - 9001                                        *
* Range enabled:  53F7 - 53F7                                        *
* Range enabled:  7801 - 7801                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontnew1font;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_4E3B[ 72] = { /* code 4E3B */
  ________,________,________,
  ________,________,________,
  ________,_X______,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,____X___,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,_XX_____,
  _____XXX,XXXXXXXX,X_______,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_4FE1[ 72] = { /* code 4FE1 */
  ________,________,________,
  ________,________,________,
  ______XX,_____XX_,________,
  ______XX,______XX,________,
  ______X_,______XX,____X___,
  _____XX_,XXXXXXXX,XXXXXX__,
  _____X__,________,________,
  ____XX__,________,________,
  ____XX__,________,___X____,
  ___XXX__,__XXXXXX,XXX_____,
  ___X_X__,________,________,
  __X__X__,________,___X____,
  _X___X__,_XXXXXXX,XXXXX___,
  _X___X__,________,________,
  _____X__,________,________,
  _____X__,__X_____,___XX___,
  _____X__,__XXXXXX,XXXX____,
  _____X__,__X_____,___X____,
  _____X__,__X_____,___X____,
  _____X__,__X_____,___X____,
  _____X__,__XXXXXX,XXXX____,
  _____X__,__X_____,___X____,
  _____X__,__X_____,___X____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_53D1[ 72] = { /* code 53D1 */
  ________,________,________,
  ________,________,________,
  ________,__X____X,________,
  _____XX_,_XX_____,XX______,
  ____XX__,_XX_____,_XX_____,
  ____X___,_X______,_XX_____,
  ___XX___,_X______,____X___,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___X____,_X______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,X_______,_XX_____,
  ________,XXXXXXXX,XXX_____,
  _______X,X_X_____,_X______,
  _______X,___X____,XX______,
  ______XX,____X__X,X_______,
  ______X_,____X__X,________,
  _____XX_,_____XX_,________,
  _____X__,_____XX_,________,
  ____X___,____XX_X,X_______,
  ___X____,__XX____,XXX_____,
  __X_____,_X______,__XXXXX_,
  _X____XX,X_______,____XX__,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_53F7[ 72] = { /* code 53F7 */
  ________,________,________,
  ________,________,________,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,________,
  ________,________,____XX__,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,_XX_____,
  _______X,_XXXXXXX,XXX_____,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,XX______,
  ________,________,XX______,
  ________,___XXXXX,X_______,
  ________,_____XXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_5904[ 72] = { /* code 5904 */
  ________,________,________,
  ________,________,________,
  ______X_,_______X,________,
  ______XX,_______X,X_______,
  ______XX,_______X,________,
  ______X_,_______X,________,
  _____XX_,___X___X,________,
  _____XXX,XXXXX__X,________,
  _____X__,___X___X,XX______,
  _____X__,__XX___X,__XX____,
  ____XX__,__XX___X,___XX___,
  ____XX__,__X____X,____XX__,
  ___X_X__,__X____X,_____X__,
  ___X__X_,_XX____X,________,
  __X___X_,_X_____X,________,
  __X____X,_X_____X,________,
  _______X,XX_____X,________,
  ________,X______X,________,
  _______X,XX_____X,________,
  ______X_,__XX____,________,
  _____X__,___XXXXX,XX______,
  ___XX___,______XX,XXXXXX__,
  __X_____,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_5C3D[ 72] = { /* code 5C3D */
  ________,________,________,
  ________,________,________,
  ________,________,__X_____,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,__X_____,
  ______X_,________,__X_____,
  ______X_,________,__X_____,
  ______X_,________,__X_____,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,____X___,________,
  _____XX_,_____X__,________,
  _____XX_,_____X__,________,
  _____X__,______X_,________,
  _____X__,__X____X,________,
  _____X__,___XX__X,X_______,
  ____X___,____X___,XXX_____,
  ____X___,____X___,__XXXXX_,
  ___X____,________,___XX___,
  __X____X,________,________,
  _X______,XXXXX___,________,
  ________,____XXX_,________,
  ________,______XX,________,
  ________,_______X,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_5DF2[ 72] = { /* code 5DF2 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,
  ________,________,_XX_____,
  ________,________,_XX_____,
  ________,________,_XX_____,
  ________,________,_XX_____,
  ____X___,________,_XX_____,
  ____XX__,________,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,_XX_____,
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,________,____X___,
  ____XX__,________,____X___,
  ____XX__,________,____X___,
  ____XX__,________,____XX__,
  ____XXXX,XXXXXXXX,XXXXXX__,
  _____XXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_5FEB[ 72] = { /* code 5FEB */
  ________,________,________,
  ____X___,________,________,
  _____X__,_____XX_,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,___X____,
  _____X__,_XXXXXXX,XXXXX___,
  _____XXX,_____X__,___X____,
  _____X_X,X____X__,___X____,
  __X__X__,X____X__,___X____,
  __X__X__,X____X__,___X____,
  _XX__X__,_____X__,___X____,
  _____X__,_____X__,___X_X__,
  _____X__,XXXXXXXX,XXXXXXX_,
  _____X__,_____X_X,________,
  _____X__,____XX_X,________,
  _____X__,____X___,X_______,
  _____X__,___XX___,X_______,
  _____X__,___X____,XX______,
  _____X__,__XX____,_XX_____,
  _____X__,_XX_____,__XX____,
  _____X__,XX______,___XXXX_,
  _____XXX,________,____X___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_606F[ 72] = { /* code 606F */
  ________,________,________,
  ________,__X_____,________,
  ________,__XX____,________,
  ________,__X_____,_X______,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,__X_____,_X______,
  ________,___XX___,________,
  _______X,X___XX__,________,
  ____X__X,X___XX__,___XX___,
  ____X__X,X_______,X___XX__,
  ___XX__X,X_______,X___XX__,
  __XXX___,X_______,_X___X__,
  ________,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_62A5[ 72] = { /* code 62A5 */
  ________,________,________,
  ________,________,________,
  _____XX_,___X____,__X_____,
  _____XX_,___XXXXX,XXXX____,
  _____XX_,___X____,__X_____,
  _____XX_,___X____,__X_____,
  _____XX_,X__X____,__X_____,
  _XXXXXXX,XX_X____,__X_____,
  _____XX_,__XX___X,XXX_____,
  _____XX_,___X____,_X______,
  _____XX_,___X____,___X____,
  _____XX_,X__XXXXX,XXXXX___,
  _____XXX,___X_X__,___X____,
  __XXXXX_,___X__X_,__X_____,
  _XX__XX_,___X__X_,__X_____,
  _____XX_,___X___X,_XX_____,
  _____XX_,___X____,XX______,
  _____XX_,___X____,XX______,
  _____XX_,___X___X,_XX_____,
  _____XX_,___X__X_,__XX____,
  _____XX_,___X_X__,___XXXX_,
  __XXXXX_,___XX___,________,
  ____XX__,___X____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_62E8[ 72] = { /* code 62E8 */
  ________,________,________,
  ________,________,________,
  _____XX_,_______X,________,
  _____XX_,___X__XX,XX______,
  _____XX_,__XX__XX,__XX____,
  _____XX_,__XX__XX,___XX___,
  _____XX_,X_X___X_,___XX___,
  __XXXXXX,_XX___X_,____X___,
  _____XX_,_XXXXXXX,XXXXXX__,
  _____XX_,__X__XX_,________,
  _____XX_,_X___XX_,________,
  _____XX_,X____X__,________,
  _____XXX,_____XXX,XXXXX___,
  ___XXXX_,____XX__,___X____,
  _XXX_XX_,____X_X_,__XX____,
  __X__XX_,____X_X_,__X_____,
  _____XX_,___X___X,_XX_____,
  _____XX_,___X___X,_X______,
  _____XX_,__X_____,X_______,
  _____XX_,_X_____X,XX______,
  _____XX_,_X____X_,_XXX____,
  ___XXX__,X___XX__,___XXXX_,
  ____XX_X,__XX____,____X___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_6545[ 72] = { /* code 6545 */
  ________,________,________,
  ________,________,________,
  _______X,_______X,X_______,
  _______X,_______X,________,
  _______X,______XX,________,
  _______X,______XX,________,
  _______X,______X_,________,
  _XXXXXXX,XXXX__XX,XXXXXX__,
  _______X,____XXX_,___X____,
  _______X,_____XX_,___X____,
  _______X,____X_X_,___X____,
  _______X,____X_X_,___X____,
  ___X___X,__X___X_,__XX____,
  ___XXXX_,XXX____X,__X_____,
  ___XX___,_XX____X,__X_____,
  ___XX___,_XX____X,__X_____,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XXXXX,XXX____X,_XX_____,
  ___XX___,_XX__XX_,__XXX___,
  ___XX___,____X___,___XXXX_,
  ________,__XX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_672A[ 72] = { /* code 672A */
  ________,________,________,
  ________,___X____,________,
  ________,___XXX__,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,_XX_____,
  _____XXX,XXXXXXXX,X_______,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXXX__,________,
  ________,_XXXX_X_,________,
  ________,XX_XX_X_,________,
  ________,X__XX__X,________,
  _______X,___XX___,X_______,
  ______X_,___XX___,XX______,
  _____X__,___XX___,_XXX____,
  ____X___,___XX___,__XXXXX_,
  __XX____,___XX___,____X___,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_7406[ 72] = { /* code 7406 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,XXXXX___,
  _______X,X__X___X,____X___,
  __XXXXX_,___X___X,____X___,
  _____X__,___X___X,____X___,
  _____X__,___X___X,____X___,
  _____X__,___XXXXX,XXXXX___,
  _____X__,___X___X,____X___,
  _____X__,X__X___X,____X___,
  __XXXXXX,___X___X,____X___,
  _____X__,___XXXXX,XXXXX___,
  _____X__,___X___X,____X___,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_X_____X,___XX___,
  _____XXX,X_XXXXXX,XXX_____,
  __XXXX__,_______X,________,
  __XX____,_______X,________,
  ________,_______X,_____X__,
  ________,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_7535[ 72] = { /* code 7535 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,___X____,________,
  ________,___X____,____X___,
  ________,___X____,____X___,
  ________,___X____,_____X__,
  ________,___XX___,____XX__,
  ________,____XXXX,XXXXX___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_7801[ 72] = { /* code 7801 */
  ________,________,________,
  ________,________,________,
  ________,________,___X____,
  _XXXXXXX,XX_XXXXX,XXXXX___,
  _____X__,__X_____,___X____,
  ____XX__,____XX__,___X____,
  ____X___,____XX__,___X____,
  ____X___,____X___,__XX____,
  ____X___,____X___,__XX____,
  ___X___X,X___X___,__X_____,
  ___XXXXX,X___X___,__X_____,
  __XXX__X,X___X___,__X_____,
  __XXX__X,X__XXXXX,XXXXXX__,
  _X_XX__X,X_______,_____X__,
  ___XX__X,X_______,_____X__,
  ___XX__X,X_______,_____X__,
  ___XX__X,XXXXXXXX,XXX_XX__,
  ___XX__X,X_______,___XXX__,
  ___XXXXX,X_______,____X___,
  ___XX__X,X_______,____X___,
  ___XX___,_______X,X___X___,
  ___X____,________,_XXXX___,
  ________,________,__XX____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_8B66[ 72] = { /* code 8B66 */
  ________,________,________,
  _____X__,________,________,
  _____XX_,_X_____X,X_______,
  _____XX_,_X__X__X,________,
  __XXXXXX,XXXX_XXX,XXXXXX__,
  ____XX__,___X__XX,__XX____,
  ___XXXXX,XXXXXX_X,__X_____,
  ___XX___,X__X_X_X,__X_____,
  __X_XXXX,X__X____,XX______,
  ____XXXX,X__X____,XX______,
  ____X__X,__X____X,__XX____,
  ________,XXX___X_,___XXX__,
  ________,_X_XXX__,________,
  ________,____X___,___XX___,
  ___XXXXX,XXXX_XXX,XXX_____,
  _____XXX,XXXXXXXX,XX______,
  ________,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ________,________,X_______,
  _____XXX,XXXXXXXX,XX______,
  _____XX_,________,XX______,
  _____XXX,XXXXXXXX,XX______,
  _____XX_,________,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_8BF7[ 72] = { /* code 8BF7 */
  ________,________,________,
  ________,______X_,________,
  ___X____,______XX,________,
  ____X___,______XX,____X___,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,______XX,________,
  ________,______XX,___X____,
  ________,__XXXXXX,XXXXX___,
  ________,______XX,________,
  _XXXXX__,______XX,____XX__,
  ____XX__,XXXXXXXX,XXXXXXX_,
  ____XX__,________,________,
  ____XX__,__XXXXXX,XXXX____,
  ____XX__,__XX____,___X____,
  ____XX__,__XX____,___X____,
  ____XX__,__XXXXXX,XXXX____,
  ____XX__,X_XX____,___X____,
  ____XX_X,__XX____,___X____,
  ____XXX_,__XXXXXX,XXXX____,
  ____XXX_,__XX____,___X____,
  ____XX__,__XX____,___X____,
  ________,__XX___X,XXXX____,
  ________,__XX____,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_9001[ 72] = { /* code 9001 */
  ________,________,________,
  ________,________,________,
  ___X____,__X_____,_XX_____,
  ____X___,___X____,_X______,
  ____XX__,___XX___,XX______,
  _____X__,____X___,X_______,
  _____X__,_______X,___XX___,
  ________,_XXXXXXX,XXXXXX__,
  ________,______X_,________,
  _____X__,______X_,________,
  _XXXXX__,______X_,____XX__,
  _____X__,XXXXXXXX,XXXXXX__,
  _____X__,______X_,________,
  _____X__,_____XX_,________,
  _____X__,_____X_X,________,
  _____X__,____XX__,XX______,
  _____X__,___XX___,__XX____,
  _____X__,__XX____,__XX____,
  ____XX__,_X______,___X____,
  __XX__XX,X_______,________,
  _XX_____,XX______,______X_,
  ________,__XXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_901A[ 72] = { /* code 901A */
  ________,________,________,
  ________,________,________,
  ________,________,__XX____,
  ___XX___,__XXXXXX,XXXX____,
  ____XX__,____XX__,XX______,
  ____XX__,_____XXX,________,
  ________,______XX,____X___,
  ________,_XXXXXXX,XXXXX___,
  ________,_X____X_,____X___,
  _____X__,_X____X_,____X___,
  __XXXX__,_XXXXXXX,XXXXX___,
  _____X__,_X____X_,____X___,
  _____X__,_X____X_,____X___,
  _____X__,_X____X_,____X___,
  _____X__,_XXXXXXX,XXXXX___,
  _____X__,_X____X_,____X___,
  _____X__,_X____X_,____X___,
  _____X__,_X____X_,____X___,
  ____XX__,_X____X_,__XXX___,
  __XX__XX,________,___X____,
  _XX_____,XX______,______X_,
  __X_____,__XXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnew1font_969C[ 72] = { /* code 969C */
  ________,________,________,
  ________,_____X__,________,
  ________,______X_,________,
  __XXXXXX,______XX,___X____,
  __X___XX,_XXXXXXX,XXXXX___,
  __X___X_,___X____,_X______,
  __X___X_,____X___,_X______,
  __X__X__,____XX__,X_______,
  __X__X__,____X___,X___XX__,
  __X_X___,_XXX_XXX,_XXX____,
  __X__X__,__X_____,___X____,
  __X___X_,__XXXXXX,XXXXX___,
  __X____X,__X_____,___X____,
  __X____X,__XXXXXX,XXXX____,
  __X____X,__X_____,___X____,
  __X____X,__X_____,___X____,
  __X_XXXX,__XXXXXX,XXXX____,
  __X__XX_,______XX,_____X__,
  __X_____,______XX,____XX__,
  __X_____,XXXXXXXX,XXXX____,
  __X_____,______XX,________,
  __X_____,______XX,________,
  __X_____,______XX,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontnew1font_CharInfo[21] = {
   {  24,  24,  3, acGUI_Fontnew1font_4E3B } /* code 4E3B */
  ,{  24,  24,  3, acGUI_Fontnew1font_4FE1 } /* code 4FE1 */
  ,{  24,  24,  3, acGUI_Fontnew1font_53D1 } /* code 53D1 */
  ,{  24,  24,  3, acGUI_Fontnew1font_53F7 } /* code 53F7 */
  ,{  24,  24,  3, acGUI_Fontnew1font_5904 } /* code 5904 */
  ,{  24,  24,  3, acGUI_Fontnew1font_5C3D } /* code 5C3D */
  ,{  24,  24,  3, acGUI_Fontnew1font_5DF2 } /* code 5DF2 */
  ,{  24,  24,  3, acGUI_Fontnew1font_5FEB } /* code 5FEB */
  ,{  24,  24,  3, acGUI_Fontnew1font_606F } /* code 606F */
  ,{  24,  24,  3, acGUI_Fontnew1font_62A5 } /* code 62A5 */
  ,{  24,  24,  3, acGUI_Fontnew1font_62E8 } /* code 62E8 */
  ,{  24,  24,  3, acGUI_Fontnew1font_6545 } /* code 6545 */
  ,{  24,  24,  3, acGUI_Fontnew1font_672A } /* code 672A */
  ,{  24,  24,  3, acGUI_Fontnew1font_7406 } /* code 7406 */
  ,{  24,  24,  3, acGUI_Fontnew1font_7535 } /* code 7535 */
  ,{  24,  24,  3, acGUI_Fontnew1font_7801 } /* code 7801 */
  ,{  24,  24,  3, acGUI_Fontnew1font_8B66 } /* code 8B66 */
  ,{  24,  24,  3, acGUI_Fontnew1font_8BF7 } /* code 8BF7 */
  ,{  24,  24,  3, acGUI_Fontnew1font_9001 } /* code 9001 */
  ,{  24,  24,  3, acGUI_Fontnew1font_901A } /* code 901A */
  ,{  24,  24,  3, acGUI_Fontnew1font_969C } /* code 969C */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop21 = {
   0x969C /* first character */
  ,0x969C /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 20] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop20 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontnew1font_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop19 = {
   0x9001 /* first character */
  ,0x9001 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontnew1font_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop18 = {
   0x8BF7 /* first character */
  ,0x8BF7 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontnew1font_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop17 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontnew1font_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop16 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontnew1font_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop15 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontnew1font_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop14 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontnew1font_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop13 = {
   0x672A /* first character */
  ,0x672A /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontnew1font_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop12 = {
   0x6545 /* first character */
  ,0x6545 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontnew1font_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop11 = {
   0x62E8 /* first character */
  ,0x62E8 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontnew1font_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop10 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  9] /* address of first character */
  ,&GUI_Fontnew1font_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop9 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  8] /* address of first character */
  ,&GUI_Fontnew1font_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop8 = {
   0x5FEB /* first character */
  ,0x5FEB /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  7] /* address of first character */
  ,&GUI_Fontnew1font_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop7 = {
   0x5DF2 /* first character */
  ,0x5DF2 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  6] /* address of first character */
  ,&GUI_Fontnew1font_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop6 = {
   0x5C3D /* first character */
  ,0x5C3D /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  5] /* address of first character */
  ,&GUI_Fontnew1font_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop5 = {
   0x5904 /* first character */
  ,0x5904 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  4] /* address of first character */
  ,&GUI_Fontnew1font_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop4 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  3] /* address of first character */
  ,&GUI_Fontnew1font_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop3 = {
   0x53D1 /* first character */
  ,0x53D1 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  2] /* address of first character */
  ,&GUI_Fontnew1font_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop2 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  1] /* address of first character */
  ,&GUI_Fontnew1font_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnew1font_Prop1 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_Fontnew1font_CharInfo[  0] /* address of first character */
  ,&GUI_Fontnew1font_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontnew1font = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontnew1font_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

