/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: newfont.h                                             *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 24                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  4F4D - 4F4D                                        *
* Range enabled:  7F6E - 7F6E                                        *
* Range enabled:  5367 - 5367                                        *
* Range enabled:  5BA4 - 5BA4                                        *
* Range enabled:  9633 - 9633                                        *
* Range enabled:  53F0 - 53F0                                        *
* Range enabled:  53A8 - 53A8                                        *
* Range enabled:  623F - 623F                                        *
* Range enabled:  536B - 536B                                        *
* Range enabled:  751F - 751F                                        *
* Range enabled:  95F4 - 95F4                                        *
* Range enabled:  7F16 - 7F16                                        *
* Range enabled:  53F7 - 53F7                                        *
* Range enabled:  8BBE - 8BBE                                        *
* Range enabled:  5907 - 5907                                        *
* Range enabled:  767B - 767B                                        *
* Range enabled:  9646 - 9646                                        *
* Range enabled:  4E2D - 4E2D                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontnewfont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_4E2D[ 72] = { /* code 4E2D */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ___X____,___X____,___XX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,___X____,___XX___,
  ___XX___,___X____,___XX___,
  ___XX___,___X____,___XX___,
  ___XX___,___X____,___XX___,
  ___XX___,___X____,___XX___,
  ___XX___,___X____,___XX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___X____,___X____,___X____,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_4F4D[ 72] = { /* code 4F4D */
  ________,________,________,
  ______X_,________,________,
  ______XX,_____X__,________,
  ______X_,_____XX_,________,
  ______X_,______X_,________,
  _____XX_,______X_,________,
  _____X__,________,___XX___,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,________,________,
  ____XX__,________,__XX____,
  ___X_X__,__X_____,_XX_____,
  __X__X__,__X_____,_XX_____,
  __X__X__,___X____,_X______,
  _X___X__,___X____,_X______,
  _____X__,___XX___,_X______,
  _____X__,___XX___,XX______,
  _____X__,___XX___,X_______,
  _____X__,____X___,X_______,
  _____X__,________,X_______,
  _____X__,_______X,________,
  _____X__,_______X,____XX__,
  _____X_X,XXXXXXXX,XXXXXXX_,
  _____X__,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_5367[ 72] = { /* code 5367 */
  ________,________,________,
  ________,________,________,
  ________,_______X,XX______,
  ___X____,___XX___,X_______,
  ___XXXXX,XXX_____,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___XXXXX,XXXXX___,X_______,
  ___X____,____X___,XXX_____,
  ___X____,____X___,X__XX___,
  ___X____,____X___,X___XX__,
  ___X____,____X___,X____X__,
  ___X____,____X___,X_______,
  ___XXXXX,XXXXX___,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X___X___,X_______,
  __XXXXXX,XXXXXX__,X_______,
  ___X____,________,X_______,
  ________,________,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_536B[ 72] = { /* code 536B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,__XX____,
  _____XXX,XXXXXXXX,XXXX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX____,__XX____,
  ________,__XX__XX,XXX_____,
  ________,__XX____,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,____XX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_53A8[ 72] = { /* code 53A8 */
  ________,________,________,
  ________,________,________,
  ________,________,___XX___,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____X___,________,__X_____,
  ____X___,____X___,__XX____,
  ____X_XX,XXXXXX__,__XX____,
  ____X___,________,__XX____,
  ____X___,____X___,__XX____,
  ____X__X,XXXXX_XX,XXXXXX__,
  ____X__X,____X___,__XX____,
  ____X__X,____X___,__XX____,
  ____X__X,____X_X_,__XX____,
  ____X__X,XXXXX__X,__XX____,
  ____X__X,_______X,X_XX____,
  ____X_X_,____X___,X_XX____,
  ____X__X,X__XX___,__XX____,
  ___XX___,X__X____,__XX____,
  ___X____,X__X____,__XX____,
  ___X____,__XXXX__,__XX____,
  __X__XXX,XX_____X,XXX_____,
  __X__X__,________,_XX_____,
  _X______,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_53F0[ 72] = { /* code 53F0 */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,_XX_____,________,
  ________,XX______,________,
  _______X,X______X,________,
  ______XX,________,XX______,
  _____XX_,________,__XX____,
  ____XX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XX_XX___,
  ____XX__,________,____X___,
  ________,________,________,
  ________,________,_X______,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_53F7[ 72] = { /* code 53F7 */
  ________,________,________,
  ________,________,________,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,________,
  ________,________,____XX__,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,_XX_____,
  _______X,_XXXXXXX,XXX_____,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,XX______,
  ________,________,XX______,
  ________,___XXXXX,X_______,
  ________,_____XXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_5907[ 72] = { /* code 5907 */
  ________,________,________,
  ________,________,________,
  ________,XXX_____,________,
  ________,XX______,X_______,
  _______X,XXXXXXXX,XX______,
  _______X,X______X,X_______,
  ______XX,_X____XX,________,
  ______X_,__X___X_,________,
  _____X__,__X__XX_,________,
  ____X___,___XXX__,________,
  ________,___XXX__,________,
  ________,_XX__XX_,________,
  ________,XX____XX,X_______,
  ______XX,________,XXXXXX__,
  ____XXXX,XXXXXXXX,XXXXXX__,
  _XXX__X_,____X___,_X______,
  ______X_,____X___,_X______,
  ______X_,____X___,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,____X___,_X______,
  ______X_,____X___,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_5BA4[ 72] = { /* code 5BA4 */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ________,____X___,____X___,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ___X____,________,___X____,
  __XX____,________,_XX_____,
  ________,________,XXX_____,
  _____XXX,XXXXXXXX,________,
  ________,_X_____X,________,
  ________,X_______,XX______,
  ______XX,________,_XX_____,
  _____XXX,XXXXXXXX,XXX_____,
  ______X_,___X____,__X_____,
  ________,___XX___,________,
  ________,___XX___,________,
  _____XXX,XXXXXXXX,XXX_____,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_623F[ 72] = { /* code 623F */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,____X___,________,
  _____XXX,XXXXXXXX,XXXX____,
  _____X__,________,___X____,
  _____X__,________,___X____,
  _____X__,________,___X____,
  _____XXX,XXXXXXXX,XXXX____,
  _____X__,____X___,________,
  _____X__,_____XX_,________,
  _____X__,_____XX_,____X___,
  _____X_X,XXXXXXXX,XXXXXX__,
  ____XX__,___XX___,________,
  ____XX__,___XX___,________,
  ____X___,___XX___,___X____,
  ____X___,___X_XXX,XXXX____,
  ____X___,__XX____,__XX____,
  ___X____,__X_____,__XX____,
  ___X____,_XX_____,__XX____,
  __X_____,XX______,__X_____,
  _X_____X,X______X,XXX_____,
  _X____X_,________,_XX_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_751F[ 72] = { /* code 751F */
  ________,________,________,
  ________,___X____,________,
  ________,___XX___,________,
  ______X_,___XX___,________,
  ______XX,___XX___,________,
  _____XX_,___XX___,________,
  _____X__,___XX___,___X____,
  _____X__,___XX___,__XXX___,
  ____X_XX,XXXXXXXX,XX______,
  ____X___,___XX___,________,
  ___X____,___XX___,________,
  ___X____,___XX___,________,
  __X_____,___XX___,________,
  _X______,___XX___,_XX_____,
  _____XXX,XXXXXXXX,XXXX____,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____XX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_767B[ 72] = { /* code 767B */
  ________,________,________,
  ________,________,________,
  ________,____X___,_X______,
  ____XXXX,XXXX_X__,_XX_____,
  ________,__X__X__,X_______,
  ____X___,_X____XX,___XX___,
  _____XX_,XX____X_,__XX____,
  _____XX_,X______X,_XX_____,
  _____X_X,______XX,X_______,
  ______X_,XXXXXXXX,XX______,
  _____X__,________,__XXX___,
  ____X___,________,___XXX__,
  __XX__XX,XXXXXXXX,XX______,
  ______XX,________,X_______,
  ______XX,________,X_______,
  ______XX,________,X_______,
  ______XX,XXXXXXXX,X_______,
  ______X_,________,X_______,
  _______X,_______X,X_______,
  ________,XX_____X,________,
  ________,_X____X_,________,
  ________,_X___X__,____XX__,
  __XXXXXX,X_XXX_XX,XXXX____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_7F16[ 72] = { /* code 7F16 */
  ________,________,________,
  ________,________,________,
  _____X__,______XX,________,
  _____X__,_______X,________,
  ____XX__,________,___XX___,
  ____X___,__XXXXXX,XXXXX___,
  ___X___X,__X_____,___XX___,
  ___X___X,X_X_____,___XX___,
  __X____X,__XXXXXX,XXXXX___,
  _XXXXXX_,__X_____,___X____,
  __X__X__,__X_____,________,
  _____X__,__XX____,_____X__,
  ____X___,_XXXXXXX,XXXXXX__,
  ___X____,_XXX__X_,_X__XX__,
  __X_XXXX,_X_X__X_,_X__XX__,
  __XX____,_X_X__X_,_X__XX__,
  ________,_X_XXXXX,XXXXXX__,
  _______X,XX_X__X_,_X__XX__,
  ___XXXX_,X__X__X_,_X__XX__,
  __XX____,X__X__X_,_X__XX__,
  _______X,___X__X_,_X__XX__,
  ______X_,___X____,__XXXX__,
  _____X__,___X____,___XX___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_7F6E[ 72] = { /* code 7F6E */
  ________,________,________,
  ________,________,________,
  ____X___,________,___XX___,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,___XX___,__X_____,
  ________,___X____,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,___X____,X_______,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X__XX__,
  _XXXXX_X,XXXXXXXX,X_XX____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_8BBE[ 72] = { /* code 8BBE */
  ________,________,________,
  ________,________,________,
  ____X___,___X____,_X______,
  _____X__,___XXXXX,XX______,
  _____XX_,___XX___,_X______,
  _____XX_,___XX___,_X______,
  ________,___X____,_X______,
  ________,___X____,_X______,
  ________,__XX____,_XXXXX__,
  _XXXXXX_,__X_____,__XXXX__,
  _____X__,_X______,__X_____,
  _____X_X,X_XXXXXX,XXXX____,
  _____X__,___X____,__X_____,
  _____X__,____X___,_XX_____,
  _____X__,____X___,_X______,
  _____X__,_____X__,XX______,
  _____X__,_X___X__,X_______,
  _____X__,X_____XX,X_______,
  _____X_X,______XX,________,
  _____XX_,_____XXX,X_______,
  _____XX_,____XX__,_XXX____,
  ________,__XX____,__XXXX__,
  _______X,XX______,____X___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_95F4[ 72] = { /* code 95F4 */
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  ______X_,________,____X___,
  ______XX,__XXXXXX,XXXXX___,
  ___XX_X_,________,____X___,
  ___X____,________,____X___,
  ___X____,X_______,____X___,
  ___X____,XXXXXXXX,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,XXXXXXX_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____XX,____X___,
  ___X____,X_____XX,____X___,
  ___X____,XXXXXXXX,____X___,
  ___X____,X_____X_,____X___,
  ___X____,________,____X___,
  ___X____,________,____X___,
  ___X____,________,_XXXX___,
  ___X____,________,__XX____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_9633[ 72] = { /* code 9633 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XX_X____,________,
  ___X____,X__XXXXX,XXXXX___,
  ___X___X,X__XX___,___XX___,
  ___X___X,___XX___,___XX___,
  ___X___X,___XX___,___XX___,
  ___X__X_,___XX___,___XX___,
  ___X__X_,___XX___,___XX___,
  ___X___X,___XX___,___XX___,
  ___X____,X__XX___,___XX___,
  ___X____,X__XXXXX,XXXXX___,
  ___X____,_X_XX___,___XX___,
  ___X____,_X_XX___,___XX___,
  ___X____,XX_XX___,___XX___,
  ___X_XXX,X__XX___,___XX___,
  ___X__XX,___XX___,___XX___,
  ___X____,___XX___,___XX___,
  ___X____,___XXXXX,XXXXX___,
  ___X____,___XX___,___XX___,
  ___X____,___XX___,___XX___,
  ___X____,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontnewfont_9646[ 72] = { /* code 9646 */
  ________,________,________,
  ________,______X_,________,
  __X____X,______XX,________,
  __XXXXXX,X_____XX,________,
  __X____X,_______X,________,
  __X___X_,_______X,________,
  __X___X_,_XXXXXXX,XXXXX___,
  __X__X__,_______X,________,
  __X__X__,_______X,________,
  __X__X__,_______X,________,
  __X___X_,_______X,____XX__,
  __X____X,XXXXXXXX,XXXXXXX_,
  __X____X,_______X,________,
  __X_____,X______X,________,
  __X_____,X_XX___X,___XX___,
  __XXX__X,X_X____X,___XX___,
  __X__XXX,__X____X,___XX___,
  __X___X_,__X____X,___XX___,
  __X_____,__X____X,___XX___,
  __X_____,__X____X,___XX___,
  __X_____,__X____X,___XX___,
  __X_____,__XXXXX_,XXXXX___,
  __X_____,________,___X____,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontnewfont_CharInfo[18] = {
   {  24,  24,  3, acGUI_Fontnewfont_4E2D } /* code 4E2D */
  ,{  24,  24,  3, acGUI_Fontnewfont_4F4D } /* code 4F4D */
  ,{  24,  24,  3, acGUI_Fontnewfont_5367 } /* code 5367 */
  ,{  24,  24,  3, acGUI_Fontnewfont_536B } /* code 536B */
  ,{  24,  24,  3, acGUI_Fontnewfont_53A8 } /* code 53A8 */
  ,{  24,  24,  3, acGUI_Fontnewfont_53F0 } /* code 53F0 */
  ,{  24,  24,  3, acGUI_Fontnewfont_53F7 } /* code 53F7 */
  ,{  24,  24,  3, acGUI_Fontnewfont_5907 } /* code 5907 */
  ,{  24,  24,  3, acGUI_Fontnewfont_5BA4 } /* code 5BA4 */
  ,{  24,  24,  3, acGUI_Fontnewfont_623F } /* code 623F */
  ,{  24,  24,  3, acGUI_Fontnewfont_751F } /* code 751F */
  ,{  24,  24,  3, acGUI_Fontnewfont_767B } /* code 767B */
  ,{  24,  24,  3, acGUI_Fontnewfont_7F16 } /* code 7F16 */
  ,{  24,  24,  3, acGUI_Fontnewfont_7F6E } /* code 7F6E */
  ,{  24,  24,  3, acGUI_Fontnewfont_8BBE } /* code 8BBE */
  ,{  24,  24,  3, acGUI_Fontnewfont_95F4 } /* code 95F4 */
  ,{  24,  24,  3, acGUI_Fontnewfont_9633 } /* code 9633 */
  ,{  24,  24,  3, acGUI_Fontnewfont_9646 } /* code 9646 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop18 = {
   0x9646 /* first character */
  ,0x9646 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 17] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop17 = {
   0x9633 /* first character */
  ,0x9633 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontnewfont_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop16 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontnewfont_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop15 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontnewfont_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop14 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontnewfont_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop13 = {
   0x7F16 /* first character */
  ,0x7F16 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontnewfont_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop12 = {
   0x767B /* first character */
  ,0x767B /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontnewfont_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop11 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontnewfont_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontnewfont_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop10 = {
   0x623F /* first character */
  ,0x623F /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  9] /* address of first character */
  ,&GUI_Fontnewfont_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop9 = {
   0x5BA4 /* first character */
  ,0x5BA4 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  8] /* address of first character */
  ,&GUI_Fontnewfont_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop8 = {
   0x5907 /* first character */
  ,0x5907 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  7] /* address of first character */
  ,&GUI_Fontnewfont_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop7 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  6] /* address of first character */
  ,&GUI_Fontnewfont_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop6 = {
   0x53F0 /* first character */
  ,0x53F0 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  5] /* address of first character */
  ,&GUI_Fontnewfont_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop5 = {
   0x53A8 /* first character */
  ,0x53A8 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  4] /* address of first character */
  ,&GUI_Fontnewfont_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop4 = {
   0x536B /* first character */
  ,0x536B /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  3] /* address of first character */
  ,&GUI_Fontnewfont_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop3 = {
   0x5367 /* first character */
  ,0x5367 /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  2] /* address of first character */
  ,&GUI_Fontnewfont_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop2 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  1] /* address of first character */
  ,&GUI_Fontnewfont_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontnewfont_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_Fontnewfont_CharInfo[  0] /* address of first character */
  ,&GUI_Fontnewfont_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontnewfont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontnewfont_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

