/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: power.h                                               *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 16                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  5BB6 - 5BB6                                        *
* Range enabled:  5EAD - 5EAD                                        *
* Range enabled:  62A5 - 62A5                                        *
* Range enabled:  8B66 - 8B66                                        *
* Range enabled:  63A7 - 63A7                                        *
* Range enabled:  5236 - 5236                                        *
* Range enabled:  5668 - 5668                                        *
* Range enabled:  8BBE - 8BBE                                        *
* Range enabled:  5907 - 5907                                        *
* Range enabled:  767B - 767B                                        *
* Range enabled:  9646 - 9646                                        *
* Range enabled:  4E2D - 4E2D                                        *
* Range enabled:  9646 - 9646                                        *
* Range enabled:  5F55 - 5F55                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontpower;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontpower_4E2D[ 32] = { /* code 4E2D */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5236[ 32] = { /* code 5236 */
  _____X__,_____X__,
  __X__X__,_____X__,
  __X__X__,_____X__,
  __XXXXXX,X_X__X__,
  _X___X__,__X__X__,
  _____X__,__X__X__,
  XXXXXXXX,XXX__X__,
  _____X__,__X__X__,
  _____X__,__X__X__,
  __XXXXXX,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__XX_,X____X__,
  __X__X_X,_____X__,
  _____X__,___X_X__,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5668[ 32] = { /* code 5668 */
  ________,________,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5907[ 32] = { /* code 5907 */
  _____X__,________,
  _____X__,________,
  ____XXXX,XXXX____,
  ___XX___,__X_____,
  _XX__X__,_X______,
  ______XX,X_______,
  ___XXX__,_XXX____,
  XXX_____,____XXX_,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5BB6[ 32] = { /* code 5BB6 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  ____XX_X,____X___,
  _XXX___X,X__X____,
  ______X_,X_X_____,
  ____XX__,XX______,
  _XXX___X,X_X_____,
  _____XX_,X__XX___,
  ___XX___,X____XX_,
  XXX___X_,X_______,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5EAD[ 32] = { /* code 5EAD */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_XXX_,____XXX_,
  __X___X_,XXXX____,
  __X__X__,___X____,
  __X__X__,___X____,
  __X_XXX_,XXXXXXX_,
  __X___X_,___X____,
  __X___X_,___X____,
  __X_X_X_,XXXXXXX_,
  _X___X__,________,
  _X___XX_,________,
  X___X__X,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_5F55[ 32] = { /* code 5F55 */
  ________,________,
  __XXXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  __X____X,____X___,
  ___X___X,X__X____,
  _____X_X,_XX_____,
  ____X__X,__X_____,
  __XX___X,___XX___,
  XX___X_X,_____XX_,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_62A5[ 32] = { /* code 62A5 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,___X_X__,
  ___X___X,____X___,
  ___X___X,________,
  ___X_X_X,XXXXXX__,
  ___XX__X,_X___X__,
  __XX___X,_X___X__,
  XX_X___X,__X_X___,
  ___X___X,__X_X___,
  ___X___X,___X____,
  ___X___X,__X_X___,
  _X_X___X,_X___X__,
  __X____X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_63A7[ 32] = { /* code 63A7 */
  ___X____,_X______,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  XXXXX_X_,______X_,
  ___X_X__,X__X_X__,
  ___X___X,____X___,
  ___XX_X_,_____X__,
  __XX____,________,
  XX_X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _X_X_XXX,XXXXXXX_,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_767B[ 32] = { /* code 767B */
  ________,X_______,
  __XXXXX_,X__X____,
  ______X_,X_X__X__,
  __X__X__,_X__X___,
  ___X_X__,_X_X____,
  ____X___,__X_____,
  ___X_XXX,XX_X____,
  __X_____,____X___,
  XX_XXXXX,XXXX_XX_,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ____X___,__X_____,
  _____X__,_X______,
  _XXXXXXX,XXXXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_8B66[ 32] = { /* code 8B66 */
  __X__X__,__X_____,
  XXXXXXXX,__X_____,
  __X__X__,_XXXXXX_,
  _XXXXXX_,XX___X__,
  X_____X_,__X_X___,
  _XXXX_X_,___X____,
  _X__X_X_,__X_X___,
  _XXXX_X_,XX___XX_,
  _____X_X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_8BBE[ 32] = { /* code 8BBE */
  ________,________,
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontpower_9646[ 32] = { /* code 9646 */
  ________,__X_____,
  _XXXXX__,__X_____,
  _X___X__,__X_____,
  _X__X__X,XXXXXX__,
  _X__X___,__X_____,
  _X_X____,__X_____,
  _X__X___,__X_____,
  _X__X_XX,XXXXXXX_,
  _X___X__,__X_____,
  _X___X__,__X_____,
  _X___X_X,__X__X__,
  _XX_X__X,__X__X__,
  _X_X___X,__X__X__,
  _X_____X,__X__X__,
  _X_____X,XXXXXX__,
  _X______,_____X__};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontpower_CharInfo[13] = {
   {  16,  16,  2, acGUI_Fontpower_4E2D } /* code 4E2D */
  ,{  16,  16,  2, acGUI_Fontpower_5236 } /* code 5236 */
  ,{  16,  16,  2, acGUI_Fontpower_5668 } /* code 5668 */
  ,{  16,  16,  2, acGUI_Fontpower_5907 } /* code 5907 */
  ,{  16,  16,  2, acGUI_Fontpower_5BB6 } /* code 5BB6 */
  ,{  16,  16,  2, acGUI_Fontpower_5EAD } /* code 5EAD */
  ,{  16,  16,  2, acGUI_Fontpower_5F55 } /* code 5F55 */
  ,{  16,  16,  2, acGUI_Fontpower_62A5 } /* code 62A5 */
  ,{  16,  16,  2, acGUI_Fontpower_63A7 } /* code 63A7 */
  ,{  16,  16,  2, acGUI_Fontpower_767B } /* code 767B */
  ,{  16,  16,  2, acGUI_Fontpower_8B66 } /* code 8B66 */
  ,{  16,  16,  2, acGUI_Fontpower_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_Fontpower_9646 } /* code 9646 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop13 = {
   0x9646 /* first character */
  ,0x9646 /* last character  */
  ,&GUI_Fontpower_CharInfo[ 12] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop12 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontpower_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontpower_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop11 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_Fontpower_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontpower_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop10 = {
   0x767B /* first character */
  ,0x767B /* last character  */
  ,&GUI_Fontpower_CharInfo[  9] /* address of first character */
  ,&GUI_Fontpower_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop9 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_Fontpower_CharInfo[  8] /* address of first character */
  ,&GUI_Fontpower_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop8 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_Fontpower_CharInfo[  7] /* address of first character */
  ,&GUI_Fontpower_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop7 = {
   0x5F55 /* first character */
  ,0x5F55 /* last character  */
  ,&GUI_Fontpower_CharInfo[  6] /* address of first character */
  ,&GUI_Fontpower_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop6 = {
   0x5EAD /* first character */
  ,0x5EAD /* last character  */
  ,&GUI_Fontpower_CharInfo[  5] /* address of first character */
  ,&GUI_Fontpower_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop5 = {
   0x5BB6 /* first character */
  ,0x5BB6 /* last character  */
  ,&GUI_Fontpower_CharInfo[  4] /* address of first character */
  ,&GUI_Fontpower_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop4 = {
   0x5907 /* first character */
  ,0x5907 /* last character  */
  ,&GUI_Fontpower_CharInfo[  3] /* address of first character */
  ,&GUI_Fontpower_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop3 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontpower_CharInfo[  2] /* address of first character */
  ,&GUI_Fontpower_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop2 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_Fontpower_CharInfo[  1] /* address of first character */
  ,&GUI_Fontpower_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontpower_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_Fontpower_CharInfo[  0] /* address of first character */
  ,&GUI_Fontpower_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontpower = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontpower_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

